#!/usr/bin/env python3
"""
Split Comparative Reasonings into Winner/Loser Traces

This script takes the exact comparative reasonings generated by the Judge LLM
(e.g., "Joke A won because X, while Joke B lost because Y") and uses a fast
local LLM to cleanly split them into two separate, prescriptive traces.

Crucially, the LLM is instructed NOT to hallucinate new reasons, but ONLY to
reformat the existing logic into a first-person generation objective.
"""

import json
import os
import torch
from tqdm import tqdm

# We will use the user's model_utils
import sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
try:
    from src.model_utils import get_model_unsloth
except ImportError:
    from model_utils import get_model_unsloth

# Configuration (repo root = two levels up from scripts/codes/)
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
INPUT_FILE = os.path.join(PROJECT_ROOT, "results", "all_winning_reasonings.jsonl")
OUTPUT_FILE = os.path.join(PROJECT_ROOT, "results", "split_causal_reasonings.jsonl")

MODEL_NAME = "unsloth/Qwen2.5-32B-Instruct-bnb-4bit"

SYSTEM_PROMPT = """You are a text extraction assistant. You will be given a judge's reasoning that explains why one joke beat another.

Your job is to split this into two clean, standalone reasoning statements.

Rules:
- Remove all references to 'Joke A', 'Joke B', 'A', or 'B'. Replace with neutral phrasing like 'the joke' or drop the label entirely.
- Do NOT add any phrases like 'This joke won because' or 'This joke lost because'. The text should be neutral — just describing humor quality, not the outcome.
- Do NOT hallucinate. Only extract what is in the original text.

Output ONLY a valid JSON object with exactly two keys:
- "winner_reason": The reasoning explaining what made the winning joke effective.
- "loser_reason": The reasoning explaining what made the losing joke ineffective.

Example Input:
"Joke A uses a clever pun on 'bark', creating surprise. Joke B is too literal and fails to deliver any incongruity."

Example Output:
{"winner_reason": "Uses a clever pun on 'bark', creating surprise and incongruity.", "loser_reason": "Too literal — states the obvious without deviation from the setup, failing to deliver incongruity."}"""


def process_reasoning_local(model, tokenizer, entry):
    """Hits the local Qwen model to split a single reasoning trace."""
    original_reasoning = entry.get('reasoning', '')
    if not original_reasoning:
        return None

    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": f"Split this reasoning:\n\n{original_reasoning}"}
    ]
    
    text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tokenizer([text], return_tensors="pt").to(model.device)
    
    try:
        with torch.no_grad():
            outputs = model.generate(**inputs, max_new_tokens=600, temperature=0.1, do_sample=False)
        
        response = tokenizer.decode(outputs[0][inputs.input_ids.shape[1]:], skip_special_tokens=True).strip()
        
        # Try to parse the JSON directly — trust the LLM
        try:
            # Find the JSON block
            start = response.find('{')
            end = response.rfind('}') + 1
            if start != -1 and end > start:
                parsed = json.loads(response[start:end])
            else:
                parsed = json.loads(response)

            winner = parsed.get('winner_reason', '').strip()
            loser = parsed.get('loser_reason', '').strip()

            # Validate: both fields must be non-empty and not the same
            if not winner or not loser or winner == loser:
                print(f"WARN: Bad split for entry (winner==loser or empty). Skipping.")
                return None

            entry['winner_reason'] = winner
            entry['loser_reason'] = loser
            return entry

        except (json.JSONDecodeError, KeyError) as je:
            print(f"WARN: JSON parse failed: {je}\nResponse was: {response[:200]}")
            return None

    except Exception as e:
        print(f"Error during generation: {e}")
        
    return None

def main():
    print(f"Loading {INPUT_FILE}...")
    
    # Load already-processed entries to support resume
    processed_ids = set()
    if os.path.exists(OUTPUT_FILE):
        with open(OUTPUT_FILE, 'r') as f:
            for line in f:
                try:
                    e = json.loads(line)
                    # Use winner+loser as a unique key
                    processed_ids.add((e.get('winner_joke_id'), e.get('loser_joke_id')))
                except:
                    pass
        print(f"Resuming: {len(processed_ids)} entries already processed.")

    # Load all entries
    all_entries = []
    with open(INPUT_FILE, 'r') as f:
        for line in f:
            if line.strip():
                all_entries.append(json.loads(line))

    # Filter out already-processed
    entries_to_process = [
        e for e in all_entries
        if (e.get('winner_joke_id'), e.get('loser_joke_id')) not in processed_ids
    ]
    print(f"Total entries: {len(all_entries)} | To process: {len(entries_to_process)}")

    # Load the local Qwen 32B model via Unsloth
    print(f"Loading Local Model {MODEL_NAME}...")
    model, tokenizer = get_model_unsloth(MODEL_NAME, max_seq_length=4096, load_in_4bit=True)

    success = 0
    failed = 0

    with open(OUTPUT_FILE, 'a') as out_f:
        for i, entry in enumerate(tqdm(entries_to_process, desc="Splitting reasonings")):
            res = process_reasoning_local(model, tokenizer, entry)
            if res:
                out_f.write(json.dumps(res) + '\n')
                out_f.flush()
                success += 1
            else:
                failed += 1

            # Print progress to stdout every 500 entries (visible in .out log)
            if (i + 1) % 500 == 0:
                print(f"[Progress] {i+1}/{len(entries_to_process)} | Success: {success} | Failed: {failed}", flush=True)

    total_done = len(processed_ids) + success
    print(f"\nDone! Success: {success} | Failed: {failed} | Total in output: {total_done}")
    print(f"Output saved to: {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
